# Generated by Django 5.1.7 on 2025-03-31 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_semestres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_admissao', models.DateField()),
                ('previsao_formatura', models.DateField()),
                ('data_exclusao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.curso')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.universidade')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.universidade'),
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre')], max_length=1)),
                ('disciplinas_cursadas', models.IntegerField()),
                ('disciplinas_aprovadas', models.IntegerField()),
                ('media_geral', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
            options={
                'unique_together': {('aluno', 'ano', 'semestre')},
            },
        ),
    ]
