# Generated by Django 5.2 on 2025-04-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefome', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('universidade', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('previsao_formatura', models.DateField()),
                ('data_exclusao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
