# Generated by Django 5.2 on 2025-04-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_rename_telefome_aluno_telefone_acompanhamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='rendimento',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
            preserve_default=False,
        ),
    ]
