# Generated by Django 5.2 on 2025-05-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_acompanhamento_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='previsao_formatura',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano_admissao',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano_formatura',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='semestre_admissão',
            field=models.IntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='semestre_formatura',
            field=models.IntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=0),
            preserve_default=False,
        ),
    ]
