# Generated by Django 5.2 on 2025-05-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_aluno_ano_admissao_alter_aluno_ano_formatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='justificativa_exclusão',
            field=models.TextField(blank=True, help_text='Informe o motivo da exclusão', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
