# Generated by Django 4.1.5 on 2023-02-09 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_remove_post_autor_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 9, 23, 52, 55, 205968, tzinfo=datetime.timezone.utc)),
        ),
    ]
